config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :projects
  resources :units
  resources :profiles
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :profile
  validates :monto_pago, :saldo_acum,:fecha_pago, :total_pago, :medio_pago, :motivo, :mes_cuota, :anio,presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  layout 'admin'
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @profiles = Profile.all
  end

  # GET /payments/1/edit
  def edit
    @profiles = Profile.all
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: "Nuevo pago creado con exito." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Actualizacion de pago exitosa." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Pago eliminado exitosamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:monto_pago, :saldo_acum, :fecha_pago, :total_pago, :medio_pago, :profile_id, :motivo, :mes_cuota, :anio)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<div class="col-md-7 col-lg-8">
<h4 class="mb-3">Pagos</h4>
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> Este pago no pudo ser guardado:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :monto_pago, class: "form-label" %>
    <%= form.number_field :monto_pago, class: "form-control" %>
  </div>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :saldo_acum, class: "form-label" %>
    <%= form.number_field :saldo_acum, class: "form-control" %>
  </div>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :fecha_pago, class: "form-label" %>
    <%= form.date_select :fecha_pago, class: "form-control" %>
  </div>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :total_pago, class: "form-label" %>
    <%= form.number_field :total_pago, class: "form-control" %>
  </div>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :medio_pago, class: "form-label" %>
    <%= form.text_field :medio_pago, class: "form-control" %>
  </div>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :profile_id, class: "form-label" %>
        <%= form.select :profile_id, @profiles.map {|p|[p.id] }, prompt: "Seleccione una opción...", class: "form-select" %>
  </div>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :motivo, class: "form-label" %>
    <%= form.text_field :motivo, class: "form-control" %>
  </div>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :mes_cuota, class: "form-label" %>
    <%= form.text_field :mes_cuota, class: "form-control" %>
  </div>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :año, class: "form-label" %>
    <%= form.number_field :anio, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: "btn btn-success"%>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editar pago</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Mostrar', @payment %> |
<%= link_to 'Volver', payments_path %>

app/views/payments/index.html.erb
<h1>Pagos</h1>
<table class="table table-striped table sm">
  <thead>
    <tr>
      <th scope="col">Monto pago</th>
      <th scope="col">Saldo acum</th>
      <th scope="col">Fecha pago</th>
      <th scope="col">Total pago</th>
      <th scope="col">Medio pago</th>
      <th scope="col">Perfil</th>
      <th scope="col">Motivo</th>
      <th scope="col">Cuota del mes:</th>
      <th scope="col">Año</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.monto_pago %></td>
        <td><%= payment.saldo_acum %></td>
        <td><%= payment.fecha_pago %></td>
        <td><%= payment.total_pago %></td>
        <td><%= payment.medio_pago %></td>
        <td><%= payment.profile.nombre %></td>
        <td><%= payment.motivo %></td>
        <td><%= payment.mes_cuota %></td>
        <td><%= payment.anio %></td>
        <td><%= link_to 'Mostrar', payment %></td>
        <td><%= link_to 'Editar', edit_payment_path(payment) %></td>
        <td><%= link_to 'Eliminar', payment, method: :delete, data: { confirm: '¿Está segur@?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Pago', new_payment_path %>

app/views/payments/new.html.erb
<h1>Nuevo Pago</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Volver', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Monto pago:</strong>
  <%= @payment.monto_pago %>
</p>

<p>
  <strong>Saldo acumulado:</strong>
  <%= @payment.saldo_acum %>
</p>

<p>
  <strong>Fecha pago:</strong>
  <%= @payment.fecha_pago %>
</p>

<p>
  <strong>Total pago:</strong>
  <%= @payment.total_pago %>
</p>

<p>
  <strong>Medio pago:</strong>
  <%= @payment.medio_pago %>
</p>

<p>
  <strong>Perfil:</strong>
  <%= @payment.profile.nombre %>
</p>

<p>
  <strong>Motivo:</strong>
  <%= @payment.motivo %>
</p>

<p>
  <strong>Mes cuota:</strong>
  <%= @payment.mes_cuota %>
</p>

<p>
  <strong>Año:</strong>
  <%= @payment.anio %>
</p>

<%= link_to 'Editar', edit_payment_path(@payment) %> |
<%= link_to 'Volver', payments_path %>