config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :projects
  resources :units
  resources :profiles
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :profile
  validates :tipo, :nombre_calle, :numero_calle, :comuna, :ciudad, :region, :zip_code, presence: true
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  layout "admin"
  before_action :set_unit, only: %i[ show edit update destroy ]

  # GET /units or /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
    @profiles=Profile.all
  end

  # GET /units/1/edit
  def edit
    @profiles=Profile.all
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to unit_url(@unit), notice: "Unidad creada con exito." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to unit_url(@unit), notice: "Unidad actualizada correctamente." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unidad eliminada exitosamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:tipo, :profile_id, :nombre_calle, :numero_calle, :comuna, :ciudad, :region, :zip_code)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<div class="col-md-7 col-lg-8">
  <h4 class="mb-3">Unidades</h4>
<%= form_with(model: unit) do |form| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> Esta unidad no puede ser gurdada:</h2>

      <ul>
        <% unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row g-3">
  <div class="col-sm-6">
    <%= form.label :tipo, class: "form-label" %>
    <%= form.text_field :tipo, class: "form-control" %>
  </div>

  <div class="col-sm-6">
    <%= form.label :profile_id, class: "form-label" %>
    <%= form.select :profile_id, @profiles.map {|p|[p.nombre, p.id] }, prompt: "Seleccione una opción...", class: "form-select" %>
    

  </div>

  <div class="col-sm-6">
    <%= form.label :nombre_calle, class: "form-label" %>
    <%= form.text_field :nombre_calle, class: "form-control" %>
  </div>

  <div class="col-sm-6">
    <%= form.label :numero_calle, class: "form-label" %>
    <%= form.text_field :numero_calle, class: "form-control" %>
  </div>

  <div class="col-sm-6">
    <%= form.label :comuna, class: "form-label" %>
    <%= form.text_field :comuna, class: "form-control" %>
  </div>

  <div class="col-sm-6">
    <%= form.label :ciudad, class: "form-label" %>
    <%= form.text_field :ciudad, class: "form-control" %>
  </div>

  <div class="col-sm-6">
    <%= form.label :region, class: "form-label" %>
    <%= form.text_field :region, class: "form-control" %>
  </div>

  <div class="col-sm-6">
    <%= form.label :zip_code, class: "form-label" %>
    <%= form.number_field :zip_code, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", class: "btn btn-success" %>
  </div>
  </div>
<% end %>
</div>

app/views/units/edit.html.erb
<h1>Editando Unidad</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Mostrar', @unit %> |
<%= link_to 'Volver', units_path %>

app/views/units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unidades</h1>

<div class="table-responsive">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th scope="col">Tipo</th>
      <th scope="col">Vecino</th>
      <th scope="col">Nombre calle</th>
      <th scope="col">Numero calle</th>
      <th scope="col">Comuna</th>
      <th scope="col">Ciudad</th>
      <th scope="col">Region</th>
      <th scope="col">Zip code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.tipo %></td>
        <td><%= unit.profile.nombre %></td>
        <td><%= unit.nombre_calle %></td>
        <td><%= unit.numero_calle %></td>
        <td><%= unit.comuna %></td>
        <td><%= unit.ciudad %></td>
        <td><%= unit.region %></td>
        <td><%= unit.zip_code %></td>
        <td><%= link_to 'Ver', unit %></td>
        <td><%= link_to 'Editar', edit_unit_path(unit) %></td>
        <td><%= link_to 'Eliminar', unit, method: :delete, data: { confirm: '¿Está segur@?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'Nueva unidad', new_unit_path %>

app/views/units/new.html.erb
<h1>Nueva Unidad</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Volver', units_path %>

app/views/units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @unit.tipo %>
</p>

<p>
  <strong>Vecino:</strong>
  <%= @unit.profile.nombre %>
</p>

<p>
  <strong>Nombre calle:</strong>
  <%= @unit.nombre_calle %>
</p>

<p>
  <strong>Numero calle:</strong>
  <%= @unit.numero_calle %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @unit.comuna %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @unit.ciudad %>
</p>

<p>
  <strong>Region:</strong>
  <%= @unit.region %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @unit.zip_code %>
</p>

<%= link_to 'Editar', edit_unit_path(@unit) %> |
<%= link_to 'Volver', units_path %>