config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :projects
  resources :units
  resources :profiles
  devise_for :users
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acticom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

   <body>
    
    
  
<header class="navbar navbar-dark sticky-top bg-success flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Comunidad Activa</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'nav-link px-3'  %> |
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to 'Perfil', profiles_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Unidades', units_path, class: "nav-link" %>
          </li>
          <li class="nav-item">


              <%= link_to 'Pagos', payments_path, class: "nav-link" %>

            
          </li>
          <li class="nav-item">
            <%= link_to 'Proyectos', projects_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Muro
            </a>
         </ul>

       </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"></h1>
        <div class="btn-toolbar mb-2 mb-md-0">
        <% if user_signed_in? %>
          <p> Hola <strong><%= current_user.email %></strong>.</p><%= link_to 'Editar usuario', edit_user_registration_path, :class => 'navbar-link' %>
        <% end %>
        </div>
      </div>

      
    <%= yield %> 



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acticom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'sign_in', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="text-center">
    
    <main class="form-signin">

    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Hola <strong><%= current_user.email %></strong>.
      <%= link_to 'Editar usuario', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
      
      
    <% else %>
      <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Ingresar", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>